### PR TITLE
simpleItem array to object

### PR DESCRIPTION
**Pull request by ksupipr**
https://github.com/dmitrif/onvif2mqtt/issues/24

### CODE REVIEW

**Comment by ksupipr** [comment]
Fixed one more error
VideoSoure/MotionAlarm => VideoSour**c**e/MotionAlarm

and fix boolMotionState
For RuleEngine/CellMotionDetector/Motion  boolMotionState in IsMotion
For VideoSource/MotionAlarm boolMotionState is State

**Comment by dmitrif** [comment]
@ksupipr Thank you! 
I think `VideoSoure/MotionAlarm` is intentional as per: https://github.com/dmitrif/onvif2mqtt/pull/5

**Comment by ksupipr** [comment]
> VideoSoure/MotionAlarm

Omg. S - Standarts )) Ok, return it.

For old D-Link cameras only VideoSourсe/MotionAlarm event for motion detection.
Tested on D-Link DCS-2103

**Comment by ksupipr** [comment]
Tested: 
D-Link DCS-2103 (only VideoSourсe/MotionAlarm event. SimpleItem State: true/false)
Hikvision DS-2CD2423G0-IW
HiWatch DS-I202 (C)
HiWatch DS-I214W (B)
HiWatch DS-I250 (B)

**Review by dmitrif — APPROVED** [review]
Thanks a bunch!

**Pull request merged**
