### PR TITLE
Adds EZViz DB-1 flashed with Hikvision FW - TESTED

### PR DESCRIPTION
**Pull request by bgilmer77**
I can confirm that EZViz DB-1 flashed with HikVision 200321 firmware works with this utility.  (Thank you!!!)

### CODE REVIEW

**Comment by scoris** [comment]
Hi, please forgive me if I am posting inappropriately, I am a total NOOB (my first use of GitHub). I believe you may have the knowledge to answer my questions, if you don’t mind please.

I want to buy a smart video doorbell with ONVIF/RTSP for all the obvious reasons. I’m just starting a home CCTV project and have decided I like the Hikvision products. I also like the look of Hik-Connect app.

I was thinking of going with the Hikvision DS-HD1 or one of its rebranded counterparts but after some research, I am now so confused as to which one with which firmware to best suit my proposed application:

- Hikvision DS-HD1 (or other rebrand eg. EZViz, RCA, Nelly’s).
- 2 or 3 Hikvision IP cameras.
- Hik-Connect android app.
- MotioneyeOS or BlueIris on old laptop in place of buying NVR. (hence need for ONVIF) for video recording.

Can you please suggest which doorbell and firmware will work for my integration of MotionEye OS (or BlueIris) and Hik-Connect?

Regards.

**Comment by bgilmer77** [comment]
@scoris, I am happy to help.  This GitHub repo is probably not the best place to post your question.  I suggest you look at [this](https://ipcamtalk.com/threads/new-rca-hsdb2a-3mp-doorbell-ip-camera.31601/page-101) forum on ipcamtalk.com.

My setup is the EZViz DB-1 flashed with the HikVision firmware.  The EZViz is about $50 less than the HikVision DS-HD1 in the U.S.  If you are not comfortable changing the firmware, then just buy the HikVision DS-HD1.
-  2 or 3 HikVision IP Cameras
Well, if they are not doorbell cameras, I guess.  It depends upon what you want to do.  But if you have other areas to monitor, then get the doorbell and a few other IP cameras.
-  Hik-Connect android app
Yes - you can use this with the doorbell camera after you flash it with the HikVision firmware.  And of course, it works directly with the HikVision DS-HD1.
-  MotioneyeOS or BlueIris
Yes - those are both solutions for NVR.  I am using Zoneminder, but these are all basically the same.

Check out the ipcamtalk forum and I think you will get good information.

**Comment by scoris** [comment]
@bgilmer77, thank you so much for taking the time to reply, especially since it probably wasn’t the right forum for my question, I was desperate for good, straight forward information.

I’d previously spent days reviewing the ipcamtalk thread you recommended, it left me very confused because many people are having different experiences. I continued to google and your github came up, I read through and felt confident in your recent experience and collaboration with @dmitrif.

Seems it makes sense to buy the EZViz DB-1 at a cheaper price, since through firmware it can be made to be like any other.

I’ll take the leap with one eye open and fingers crossed!
Thanks again. Appreciated.

**Comment by dmitrif** [comment]
Thank you! Merging.

**Comment by dmitrif** [comment]
@all-contributors please add @bgilmer77  for docs

**Pull request merged**
